using System;

public class ReportGenerator
{
    private Inventory inventory;

    public ReportGenerator(Inventory inventory)
    {
        this.inventory = inventory;
    }

    public void GenerateSalesReport(Employee employee)
{
    // Placeholder sales report content
    string salesReportContent = "Sales Report:\n";

    // Get the sales data from the inventory
    List<Sale> sales = inventory.GetSales();

    // Iterate over each sale and add it to the report content
    foreach (Sale sale in sales)
    {
        salesReportContent += $"{sale.ProductName}: {sale.QuantitySold} units sold\n";
    }

    // Output the report content along with employee information
    Console.WriteLine($"Sales Report generated by: {employee.Name} (Employee ID: {employee.EmployeeID})");
    Console.WriteLine(salesReportContent);
}
public void GenerateInventoryReport()
{
    List<Product> products = inventory.GetAllProducts();
    string inventoryReportContent = "Inventory Report:\n";
    foreach (var product in products)
    {
        inventoryReportContent += $"- Product: {product.Name}, Quantity In Stock: {product.QuantityInStock}, Price: {product.Price}\n";
    }

    // Output the inventory report content
    Console.WriteLine("Generating Inventory Report...");
    Console.WriteLine(inventoryReportContent);
    Console.WriteLine("Inventory Report generated successfully!");
}
public void GeneratePopularProductsReport()
{
    List<Product> popularProducts = inventory.GetPopularProducts();
    string popularProductsReportContent = "Popular Products Report:\n";
    foreach (var product in popularProducts)
    {
        popularProductsReportContent += $"- Product: {product.Name}, Quantity Sold: {product.SalesCount}\n";
    }

    // Output the popular products report content
    Console.WriteLine("Generating Popular Products Report...");
    Console.WriteLine(popularProductsReportContent);
    Console.WriteLine("Popular Products Report generated successfully!");
}
}